#include <vdso/bits.h>
#define CPSW_VLAN_AWARE		BIT(1)
#define CPSW_RX_VLAN_ENCAP	BIT(2)
#define CPDMA_TX_PRIORITY_MAP	0x76543210
#define CPSW2_HOST_PORT_OFFSET	0x108
#define CPSW_FIFO_NORMAL_MODE		(0 << 16)
